### ISSUE TITLE
In the code of x509_hierarchy, it seems that a generalized tree is implemented by itself. Have you considered modifying it to use the generalized tree implementation in the library?

### ISSUE THREAD

**Issue by Elsa-is-My-Muse** [EVerest/libevse-security#85]
### Describe the problem

In the code of x509_hierarchy, it seems that a generalized tree is implemented by itself. Have you considered modifying it to use the generalized tree implementation in the library?

### Describe your solution

In the code of x509_hierarchy, it seems that a generalized tree is implemented by itself. Have you considered modifying it to use the generalized tree implementation in the library?

### Additional context

In the code of x509_hierarchy, it seems that a generalized tree is implemented by itself. Have you considered modifying it to use the generalized tree implementation in the library?

**Comment by AssemblyJohn** [comment]
Since we do not have in the standard library a generalized tree, out custom implementation had to be used. Since it is very specifically used we did not think that a separation of the tree from the hierarchy is necessary at the moment.
